version: '3.8'

services:
  uav-simulator:
    build: .
    container_name: uav-simulator
    ports:
      - "8000:8000"  # API port
      - "8050:8050"  # Dashboard port
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app/src
      - LOG_LEVEL=INFO
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - uav-network

  redis:
    image: redis:7-alpine
    container_name: uav-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - uav-network

  postgres:
    image: postgres:15-alpine
    container_name: uav-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=uav_simulator
      - POSTGRES_USER=uav_user
      - POSTGRES_PASSWORD=uav_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - uav-network

  nginx:
    image: nginx:alpine
    container_name: uav-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - uav-simulator
    restart: unless-stopped
    networks:
      - uav-network

volumes:
  redis_data:
  postgres_data:

networks:
  uav-network:
    driver: bridge
